import { Client } from 'ssh2';
import dotenv from 'dotenv';
import { clearSshPassword, createSshConfig } from './ssh_config.js';

dotenv.config();

const conn = new Client();
const remoteProjectDir = process.env.SERVER_PROJECT_DIR || '/var/www/university-marketplace';
const apiPort = Number.parseInt(process.env.SERVER_API_PORT || '4099', 10);

if (!/^\/[A-Za-z0-9._/-]+$/.test(remoteProjectDir) || !Number.isInteger(apiPort) || apiPort < 1 || apiPort > 65535) {
  throw new Error('Invalid SERVER_PROJECT_DIR or SERVER_API_PORT');
}

const config = createSshConfig();

conn.on('ready', () => {
  clearSshPassword(config);
  console.log('SSH client connected. Starting locked deployment transaction...');

  const script = [
    'set -Eeuo pipefail',
    'umask 027',
    'exec 9>/run/lock/intitrade-deploy.lock',
    'if ! flock -n 9; then echo "Another IntiTrade deployment is already running" >&2; exit 75; fi',
    `PROJECT_DIR=${remoteProjectDir}`,
    `API_PORT=${apiPort}`,
    'APP_GROUP="${INTITRADE_APP_GROUP:-intitrade}"',
    'BUILD_DIR=""',
    'ENV_BACKUP=""',
    'PREVIOUS_VERSION=""',
    'PREVIOUS_BACKEND_TARGET=""',
    'PREVIOUS_BACKEND_APP_VERSION=""',
    'PREVIOUS_SCHEMA_COMPATIBILITY="legacy"',
    'EXPECTED_SCHEMA_COMPATIBILITY=""',
    'PREVIOUS_FRONTEND_TARGET=""',
    'RELEASE=""',
    'NODE_BIN=""',
    'NGINX_TRANSACTION_DIR=""',
    'NGINX_CONFIGURED=0',
    'BACKEND_ACTIVATED=0',
    'NEW_BACKEND_VERIFIED=0',
    'FRONTEND_ACTIVATED=0',
    'SCHEMA_MUTATION_STARTED=0',
    'SCHEMA_MIGRATIONS_COMPLETE=0',
    'MAINTENANCE_ENTERED=0',
    'SCHEMA_STATE_DIR=/var/lib/intitrade-deploy',
    'SCHEMA_STATE_FILE=/var/lib/intitrade-deploy/schema-compatibility',
    'SCHEMA_PENDING_FILE=/var/lib/intitrade-deploy/schema-compatibility.pending',
    'MAINTENANCE_STATE_FILE=/var/lib/intitrade-deploy/maintenance.json',
    'UPLOAD_CLEANUP_CRON=/etc/cron.d/intitrade-upload-cleanup',
    'UPLOAD_CLEANUP_PAUSED=/var/lib/intitrade-deploy/intitrade-upload-cleanup.paused',
    'validate_schema_compatibility() {',
    '  [[ "$1" =~ ^[a-z0-9][a-z0-9._-]{2,63}$ ]]',
    '}',
    'read_release_compatibility() {',
    '  local release_dir="$1" compatibility="legacy"',
    '  if [ -s "$release_dir/.schema-compatibility" ]; then compatibility="$(cat "$release_dir/.schema-compatibility")"; fi',
    '  validate_schema_compatibility "$compatibility" || return 1',
    '  printf "%s\\n" "$compatibility"',
    '}',
    'run_predeploy_checks() {',
    '  local predeploy_source="$BUILD_DIR/backend/prisma/predeploy-data-checks.sql" predeploy_wrapped="$BUILD_DIR/predeploy-data-checks.read-only.sql"',
    '  [ -s "$predeploy_source" ] || return 0',
    '  echo "Running read-only production data preconditions before the schema boundary"',
    '  PREDEPLOY_SOURCE="$predeploy_source" PREDEPLOY_WRAPPED="$predeploy_wrapped" "$NODE_BIN" --eval \'const fs = require("node:fs"); const source = fs.readFileSync(process.env.PREDEPLOY_SOURCE, "utf8"); const forbidden = /(?:\\bbegin\\s+(?:transaction|work)\\b|\\bbegin\\s*;|\\b(?:commit|rollback|savepoint|release|set|insert|update|delete|merge|alter|create|drop|truncate|grant|revoke|copy|call|vacuum|reindex|cluster|refresh)\\b)/i; if (forbidden.test(source)) throw new Error("Predeploy data checks must remain read-only and cannot control their transaction"); fs.writeFileSync(process.env.PREDEPLOY_WRAPPED, `BEGIN TRANSACTION READ ONLY;\\n${source}\\nCOMMIT;\\n`);\'',
    '  chown "root:$APP_GROUP" "$predeploy_wrapped"',
    '  chmod 0640 "$predeploy_wrapped"',
    '  runuser -u intitrade -- env -u DATABASE_URL HOME=/var/lib/intitrade NODE_ENV=production "$NODE_BIN" --env-file="$PROJECT_DIR/backend/.env" "$BUILD_DIR/backend/node_modules/prisma/build/index.js" db execute --schema "$BUILD_DIR/backend/prisma/schema.prisma" --file "$predeploy_wrapped"',
    '  rm -f -- "$predeploy_wrapped"',
    '}',
    'restore_runtime_environment() {',
    '  if [ -n "$ENV_BACKUP" ] && [ -f "$ENV_BACKUP" ]; then',
    '    cp -a -- "$ENV_BACKUP" "$PROJECT_DIR/backend/.env" || return 1',
    '    if getent group "$APP_GROUP" >/dev/null 2>&1; then chown "root:$APP_GROUP" "$PROJECT_DIR/backend/.env" && chmod 0640 "$PROJECT_DIR/backend/.env" || return 1; fi',
    '  fi',
    '}',
    'wait_for_backend_release() {',
    '  local expected_version="$1" compatibility="$2" attempt health_status health rollback_health',
    '  for attempt in $(seq 1 30); do',
    '    if systemctl is-active --quiet intitrade-api.service; then',
    '      health_status="$(curl --silent --connect-timeout 2 --max-time 5 --output "$BUILD_DIR/recovery-ready.json" --write-out "%{http_code}" "http://127.0.0.1:$API_PORT/api/health/ready" 2>/dev/null || true)"',
    '      if [ "$health_status" = "200" ]; then',
    '        health="$(cat "$BUILD_DIR/recovery-ready.json" 2>/dev/null || true)"',
    '        if verify_health_json "$health" "$expected_version"; then return 0; fi',
    '      elif [ "$health_status" = "404" ] && [ "$compatibility" = "legacy" ]; then',
    '        rollback_health="$(curl --fail --silent --connect-timeout 2 --max-time 5 "http://127.0.0.1:$API_PORT/api/health" 2>/dev/null || true)"',
    '        if verify_ok_json "$rollback_health"; then return 0; fi',
    '      fi',
    '    fi',
    '    sleep 1',
    '  done',
    '  return 1',
    '}',
    'start_api_service() {',
    '  systemctl stop intitrade-maintenance.service >/dev/null 2>&1 || true',
    '  systemctl disable intitrade-maintenance.service >/dev/null 2>&1 || true',
    '  systemctl enable intitrade-api.service >/dev/null || return 1',
    '  systemctl restart intitrade-api.service || return 1',
    '}',
    'enter_schema_maintenance() {',
    '  local attempt maintenance_status maintenance_body maintenance_tmp="$SCHEMA_STATE_DIR/.maintenance.$$.tmp"',
    '  mkdir -p "$SCHEMA_STATE_DIR" || return 1',
    '  chown root:root "$SCHEMA_STATE_DIR" && chmod 0755 "$SCHEMA_STATE_DIR" || return 1',
    '  printf "{\\\"enteredAt\\\":\\\"%s\\\",\\\"schemaCompatibility\\\":\\\"%s\\\",\\\"reason\\\":\\\"deployment-recovery\\\"}\\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$EXPECTED_SCHEMA_COMPATIBILITY" > "$maintenance_tmp" || return 1',
    '  chown root:root "$maintenance_tmp" && chmod 0644 "$maintenance_tmp" && mv -f -- "$maintenance_tmp" "$MAINTENANCE_STATE_FILE" || return 1',
    '  if systemctl cat intitrade-api.service >/dev/null 2>&1; then systemctl stop intitrade-api.service >/dev/null 2>&1 || return 1; fi',
    '  systemctl disable intitrade-api.service >/dev/null 2>&1 || true',
    '  if [ -f "$UPLOAD_CLEANUP_CRON" ]; then cp -a -- "$UPLOAD_CLEANUP_CRON" "$UPLOAD_CLEANUP_PAUSED" || return 1; rm -f -- "$UPLOAD_CLEANUP_CRON" || return 1; fi',
    '  exec 8>/run/lock/intitrade-backup.lock',
    '  flock -w 30 8 || { echo "CRITICAL: an existing backup or media cleanup did not quiesce" >&2; return 1; }',
    '  systemctl enable --now intitrade-maintenance.service >/dev/null || return 1',
    '  for attempt in $(seq 1 15); do',
    '    maintenance_status="$(curl --silent --connect-timeout 2 --max-time 3 --output "$SCHEMA_STATE_DIR/maintenance-health.json" --write-out "%{http_code}" "http://127.0.0.1:$API_PORT/api/health/ready" 2>/dev/null || true)"',
    '    maintenance_body="$(cat "$SCHEMA_STATE_DIR/maintenance-health.json" 2>/dev/null || true)"',
    '    if [ "$maintenance_status" = "503" ] && verify_maintenance_json "$maintenance_body" && systemctl is-active --quiet intitrade-maintenance.service; then',
    '      MAINTENANCE_ENTERED=1',
    '      echo "CRITICAL: incompatible schema transition is in explicit API maintenance mode" >&2',
    '      return 0',
    '    fi',
    '    sleep 1',
    '  done',
    '  echo "CRITICAL: the explicit maintenance responder did not become ready" >&2',
    '  return 1',
    '}',
    'recover_compatible_backend() {',
    '  restore_runtime_environment || return 1',
    '  PROJECT_DIR="$PROJECT_DIR" BACKEND_RELEASE_MODE=rollback BACKEND_ROLLBACK_TARGET="$PREVIOUS_BACKEND_TARGET" BACKEND_REQUIRED_SCHEMA_COMPATIBILITY="$PREVIOUS_SCHEMA_COMPATIBILITY" bash "$PROJECT_DIR/deploy/build-backend-release.sh" || return 1',
    '  restored_backend="$(readlink -f "$PROJECT_DIR/backend/runtime-current" 2>/dev/null || true)"',
    '  [ -n "$PREVIOUS_BACKEND_TARGET" ] && [ "$restored_backend" = "$PREVIOUS_BACKEND_TARGET" ] || return 1',
    '  start_api_service || return 1',
    '  wait_for_backend_release "$PREVIOUS_BACKEND_APP_VERSION" "$PREVIOUS_SCHEMA_COMPATIBILITY" || return 1',
    '  rm -f -- "$MAINTENANCE_STATE_FILE"',
    '}',
    'resume_unchanged_backend() {',
    '  restore_runtime_environment || return 1',
    '  if [ -f "$UPLOAD_CLEANUP_PAUSED" ]; then cp -a -- "$UPLOAD_CLEANUP_PAUSED" "$UPLOAD_CLEANUP_CRON" || return 1; chmod 0644 "$UPLOAD_CLEANUP_CRON" || return 1; rm -f -- "$UPLOAD_CLEANUP_PAUSED" || return 1; fi',
    '  start_api_service || return 1',
    '  wait_for_backend_release "$PREVIOUS_BACKEND_APP_VERSION" "$PREVIOUS_SCHEMA_COMPATIBILITY" || return 1',
    '  rm -f -- "$MAINTENANCE_STATE_FILE"',
    '}',
    'recover_forward_backend() {',
    '  current_backend="$(readlink -f "$PROJECT_DIR/backend/runtime-current" 2>/dev/null || true)"',
    '  if [ "$NEW_BACKEND_VERIFIED" -eq 1 ] && [ "$current_backend" = "$RELEASE" ] && wait_for_backend_release "$EXPECTED_VERSION" "$EXPECTED_SCHEMA_COMPATIBILITY"; then rm -f -- "$MAINTENANCE_STATE_FILE"; return 0; fi',
    '  PROJECT_DIR="$PROJECT_DIR" BACKEND_RELEASE_MODE=roll-forward BACKEND_ROLLFORWARD_TARGET="$RELEASE" BACKEND_REQUIRED_SCHEMA_COMPATIBILITY="$EXPECTED_SCHEMA_COMPATIBILITY" bash "$PROJECT_DIR/deploy/build-backend-release.sh" || return 1',
    '  PROJECT_DIR="$PROJECT_DIR" SERVER_API_PORT="$API_PORT" OPERATIONS_MODE=activate PROJECT_PERMISSIONS_PREPARED=1 bash "$PROJECT_DIR/deploy/configure-operations.sh" || return 1',
    '  start_api_service || return 1',
    '  wait_for_backend_release "$EXPECTED_VERSION" "$EXPECTED_SCHEMA_COMPATIBILITY" || return 1',
    '  rm -f -- "$MAINTENANCE_STATE_FILE"',
    '}',
    'rollback_and_cleanup() {',
    '  status=$?',
    '  rollback_failed=0',
    '  trap - EXIT HUP INT TERM',
    '  set +e',
    '  if [ "$status" -ne 0 ]; then',
    '    recovery_mode="unchanged"',
    '    echo "Deployment failed with status $status; selecting a schema-compatible recovery path" >&2',
    '    if [ "$FRONTEND_ACTIVATED" -eq 1 ]; then',
    '      if ! PROJECT_DIR="$PROJECT_DIR" FRONTEND_RELEASE_MODE=rollback FRONTEND_ROLLBACK_TARGET="$PREVIOUS_FRONTEND_TARGET" bash "$PROJECT_DIR/deploy/build-frontend-release.sh"; then echo "CRITICAL: frontend rollback command failed" >&2; rollback_failed=1; fi',
    '      restored_frontend="$(readlink -f "$PROJECT_DIR/frontend/current" 2>/dev/null || true)"',
    '      if [ -z "$PREVIOUS_FRONTEND_TARGET" ] || [ "$restored_frontend" != "$PREVIOUS_FRONTEND_TARGET" ]; then echo "CRITICAL: frontend rollback target mismatch" >&2; rollback_failed=1; fi',
    '    fi',
    '    selected_recovery="$(bash "$PROJECT_DIR/deploy/select-deployment-recovery.sh" "$PREVIOUS_SCHEMA_COMPATIBILITY" "$EXPECTED_SCHEMA_COMPATIBILITY" "$SCHEMA_MUTATION_STARTED" "$SCHEMA_MIGRATIONS_COMPLETE" "$BACKEND_ACTIVATED" "$MAINTENANCE_ENTERED" 2>/dev/null || printf "maintenance")"',
    '    if [ "$selected_recovery" = "roll-forward" ]; then',
    '      if [ -n "$RELEASE" ] && recover_forward_backend; then',
    '        recovery_mode="roll-forward"',
    '        echo "The migrated schema remains paired with the verified forward backend; the incompatible previous backend was not reactivated" >&2',
    '      else',
    '        if ! enter_schema_maintenance; then rollback_failed=1; fi',
    '        recovery_mode="maintenance"',
    '        status=70',
    '      fi',
    '    elif [ "$selected_recovery" = "maintenance" ]; then',
    '      if ! enter_schema_maintenance; then rollback_failed=1; fi',
    '      recovery_mode="maintenance"',
    '      status=70',
    '    elif [ "$selected_recovery" = "resume-previous" ]; then',
    '      if resume_unchanged_backend; then',
    '        recovery_mode="precondition-abort"',
    '      else',
    '        if ! enter_schema_maintenance; then rollback_failed=1; fi',
    '        recovery_mode="maintenance"',
    '        status=70',
    '      fi',
    '    elif [ "$selected_recovery" = "compatible-rollback" ]; then',
    '      if recover_compatible_backend; then recovery_mode="compatible-rollback"; else echo "CRITICAL: compatible backend rollback failed" >&2; rollback_failed=1; fi',
    '    else',
    '      if ! restore_runtime_environment; then echo "CRITICAL: runtime environment restore failed" >&2; rollback_failed=1; fi',
    '    fi',
    '    if [ "$NGINX_CONFIGURED" -eq 1 ] && [ -n "$NGINX_TRANSACTION_DIR" ]; then',
    '      if ! PROJECT_DIR="$PROJECT_DIR" NGINX_MODE=rollback NGINX_TRANSACTION_DIR="$NGINX_TRANSACTION_DIR" bash "$PROJECT_DIR/deploy/configure-intitrade-nginx.sh"; then echo "CRITICAL: Nginx rollback failed" >&2; rollback_failed=1; fi',
    '    fi',
    '    mkdir -p /var/log/intitrade',
    '    printf "{\\\"deployedAt\\\":\\\"%s\\\",\\\"commit\\\":\\\"%s\\\",\\\"status\\\":\\\"failed\\\",\\\"recovery\\\":\\\"%s\\\"}\\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "${EXPECTED_VERSION:-unknown}" "$recovery_mode" >> /var/log/intitrade/deployments.jsonl',
    '    if [ "$rollback_failed" -ne 0 ]; then echo "CRITICAL: deployment recovery was incomplete" >&2; status=70; fi',
    '  fi',
    '  if [ -n "$BUILD_DIR" ]; then rm -rf -- "$BUILD_DIR"; fi',
    '  if [ -n "$ENV_BACKUP" ]; then rm -f -- "$ENV_BACKUP"; fi',
    '  exit "$status"',
    '}',
    'trap rollback_and_cleanup EXIT',
    "trap 'exit 130' HUP INT TERM",
    'verify_health_json() {',
    '  HEALTH_JSON="$1" EXPECTED_VERSION="$2" "$NODE_BIN" --eval \'try { const value = JSON.parse(process.env.HEALTH_JSON); process.exit(value.ready === true && value.version === process.env.EXPECTED_VERSION ? 0 : 1); } catch { process.exit(1); }\'',
    '}',
    'verify_ok_json() {',
    '  HEALTH_JSON="$1" "$NODE_BIN" --eval \'try { const value = JSON.parse(process.env.HEALTH_JSON); process.exit(value.ok === true ? 0 : 1); } catch { process.exit(1); }\'',
    '}',
    'verify_maintenance_json() {',
    '  HEALTH_JSON="$1" "$NODE_BIN" --eval \'try { const value = JSON.parse(process.env.HEALTH_JSON); process.exit(value.ok === false && value.ready === false && value.maintenance === true && value.code === "DEPLOYMENT_MAINTENANCE" ? 0 : 1); } catch { process.exit(1); }\'',
    '}',
    'find_entry_asset() {',
    '  HTML_FILE="$1" "$NODE_BIN" --eval \'const fs = require("node:fs"); const html = fs.readFileSync(process.env.HTML_FILE, "utf8"); const values = [...html.matchAll(/\\bsrc\\s*=\\s*["\\x27]([^"\\x27]+\\.js)["\\x27]/gi)].map((match) => match[1]); const value = values.find((item) => item.startsWith("/assets/")); if (!value) process.exit(1); process.stdout.write(value);\'',
    '}',
    'verify_frontend_html() {',
    '  HTML_FILE="$1" EXPECTED_ENTRY_ASSET="$EXPECTED_ENTRY_ASSET" EXPECTED_FRONTEND_VERSION="$EXPECTED_VERSION" "$NODE_BIN" --eval \'const fs = require("node:fs"); const html = fs.readFileSync(process.env.HTML_FILE, "utf8"); const values = [...html.matchAll(/\\bsrc\\s*=\\s*["\\x27]([^"\\x27]+)["\\x27]/gi)].map((match) => match[1]); const parseAttributes = (tag) => Object.fromEntries([...tag.matchAll(/\\b([A-Za-z_:][-A-Za-z0-9_:.]*)\\s*=\\s*["\\x27]([^"\\x27]*)["\\x27]/g)].map((match) => [match[1].toLowerCase(), match[2]])); const releaseMatches = [...html.matchAll(/<meta\\b[^>]*>/gi)].some((match) => { const attributes = parseAttributes(match[0]); return attributes.name === "intitrade-release" && attributes.content === process.env.EXPECTED_FRONTEND_VERSION; }); process.exit(values.includes(process.env.EXPECTED_ENTRY_ASSET) && releaseMatches ? 0 : 1);\'',
    '}',
    'verify_public_frontend() {',
    '  local base_url="$1" output_file="$2" attempt asset_type',
    '  for attempt in $(seq 1 6); do',
    '    if curl --noproxy "*" --fail --silent --show-error --connect-timeout 2 --max-time 3 --header "Cache-Control: no-cache" --header "Pragma: no-cache" "${base_url}/?deploy=${VERIFY_TOKEN}-${attempt}" --output "$output_file" \\',
    '      && verify_frontend_html "$output_file"; then',
    '      rm -f "${output_file}.asset" "${output_file}.asset.tmp"',
    '      if asset_type="$(curl --noproxy "*" --fail --silent --show-error --connect-timeout 2 --max-time 3 --header "Cache-Control: no-cache" --header "Pragma: no-cache" "${base_url}${EXPECTED_ENTRY_ASSET}?deploy=${VERIFY_TOKEN}-${attempt}" --output "${output_file}.asset.tmp" --write-out "%{content_type}" 2>/dev/null)"; then',
    '        case "$asset_type" in',
    '          application/javascript*|text/javascript*) if [ -s "${output_file}.asset.tmp" ]; then mv -- "${output_file}.asset.tmp" "${output_file}.asset"; return 0; fi ;;',
    '        esac',
    '      fi',
    '      rm -f "${output_file}.asset.tmp"',
    '    fi',
    '    sleep 1',
    '  done',
    '  echo "Public frontend did not expose $EXPECTED_ENTRY_ASSET at $base_url" >&2',
    '  return 1',
    '}',
    'verify_public_health() {',
    '  local base_url="$1" attempt public_health',
    '  for attempt in $(seq 1 6); do',
    '    public_health="$(curl --noproxy "*" --fail --silent --show-error --connect-timeout 2 --max-time 3 --header "Cache-Control: no-cache" "${base_url}/api/health/ready?deploy=${VERIFY_TOKEN}-${attempt}" 2>/dev/null || true)"',
    '    if verify_health_json "$public_health" "$EXPECTED_VERSION"; then return 0; fi',
    '    sleep 1',
    '  done',
    '  echo "Public readiness did not expose release $EXPECTED_VERSION at $base_url" >&2',
    '  return 1',
    '}',

    'echo "[1/12] Verifying and updating the Git worktree"',
    'cd "$PROJECT_DIR"',
    'test -d .git',
    'PREVIOUS_VERSION="$(git rev-parse --short=12 HEAD)"',
    'if [ -f backend/.env ]; then ENV_BACKUP="/run/intitrade-env.$$.backup"; cp -a -- backend/.env "$ENV_BACKUP"; fi',
    'git diff --quiet',
    'git diff --cached --quiet',
    'git fetch origin main',
    'if git show-ref --verify --quiet refs/heads/main; then git switch main; else git switch -c main --track origin/main; fi',
    'git merge --ff-only origin/main',
    'EXPECTED_VERSION="$(git rev-parse --short=12 HEAD)"',
    'EXPECTED_SCHEMA_COMPATIBILITY="$(cat deploy/backend-schema-compatibility)"',
    'validate_schema_compatibility "$EXPECTED_SCHEMA_COMPATIBILITY" || { echo "Invalid deploy/backend-schema-compatibility marker" >&2; exit 78; }',

    'echo "[2/12] Configuring production runtime and preserving rollback releases"',
    'PROJECT_DIR="$PROJECT_DIR" BACKEND_RELEASE_MODE=preserve-current BACKEND_RELEASE_VERSION="$PREVIOUS_VERSION" bash deploy/build-backend-release.sh',
    'PREVIOUS_BACKEND_TARGET="$(readlink -f backend/runtime-current)"',
    'PREVIOUS_BACKEND_APP_VERSION="$(cat "$PREVIOUS_BACKEND_TARGET/.app-version")"',
    'PREVIOUS_SCHEMA_COMPATIBILITY="$(read_release_compatibility "$PREVIOUS_BACKEND_TARGET")"',
    'test -n "$PREVIOUS_BACKEND_TARGET"',
    'test -n "$PREVIOUS_BACKEND_APP_VERSION"',
    'PROJECT_DIR="$PROJECT_DIR" SERVER_API_PORT="$API_PORT" APP_VERSION="$EXPECTED_VERSION" bash deploy/configure-production-env.sh',
    'PROJECT_DIR="$PROJECT_DIR" SERVER_API_PORT="$API_PORT" OPERATIONS_MODE=prepare bash deploy/configure-operations.sh',
    'NODE_BIN="$(command -v node)"',
    'mkdir -p "$SCHEMA_STATE_DIR"',
    'chown root:root "$SCHEMA_STATE_DIR"',
    'chmod 0755 "$SCHEMA_STATE_DIR"',

    'echo "[3/12] Creating an isolated disposable build tree"',
    'BUILD_DIR="/var/lib/intitrade-build/$EXPECTED_VERSION"',
    'rm -rf -- "$BUILD_DIR"',
    'mkdir -p "$BUILD_DIR"',
    'git archive HEAD | tar -x -C "$BUILD_DIR"',
    'chown -R intitrade-build:intitrade-build "$BUILD_DIR"',

    'echo "[4/12] Building and testing the backend as the isolated build user"',
    `runuser -u intitrade-build -- env HOME=/var/lib/intitrade-build NODE_ENV=test DATABASE_URL=postgresql://build@127.0.0.1:5432/build bash -c 'cd "$1/backend" && npm ci --no-audit --no-fund && npm run build && npm test' -- "$BUILD_DIR"`,

    'echo "[5/12] Building and type-checking the frontend as the isolated build user"',
    `runuser -u intitrade-build -- env HOME=/var/lib/intitrade-build NODE_ENV=production bash -c 'cd "$1/frontend" && npm ci --include=dev --no-audit --no-fund && npm run typecheck && npm run build' -- "$BUILD_DIR"`,
    'chmod -R a+rX "$BUILD_DIR"',

    'echo "[6/12] Staging immutable backend and frontend releases"',
    'PROJECT_DIR="$PROJECT_DIR" BACKEND_BUILD_DIR="$BUILD_DIR/backend" BACKEND_SCHEMA_COMPATIBILITY_FILE="$BUILD_DIR/deploy/backend-schema-compatibility" BACKEND_RELEASE_MODE=stage bash deploy/build-backend-release.sh',
    'PROJECT_DIR="$PROJECT_DIR" FRONTEND_BUILD_DIR="$BUILD_DIR/frontend" FRONTEND_RELEASE_MODE=stage bash deploy/build-frontend-release.sh',
    'PREVIOUS_FRONTEND_TARGET="$(readlink -f frontend/current)"',
    'test -n "$PREVIOUS_FRONTEND_TARGET"',
    'RELEASE="$(cat backend/.pending-runtime-release)"',
    'test "$(read_release_compatibility "$RELEASE")" = "$EXPECTED_SCHEMA_COMPATIBILITY"',
    'runuser -u intitrade -- env HOME=/var/lib/intitrade bash -c \'cd "$1" && exec "$2" --input-type=module --eval "$3"\' -- "$RELEASE" "$NODE_BIN" \'await import("./dist/env.js")\'',
    'run_predeploy_checks',

    'echo "[7/12] Creating a verified pre-migration backup"',
    'PROJECT_DIR="$PROJECT_DIR" bash deploy/backup-intitrade.sh',
    '# Abort with the old API still active if data changed while the backup ran.',
    'run_predeploy_checks',
    'CURRENT_SCHEMA_COMPATIBILITY="$PREVIOUS_SCHEMA_COMPATIBILITY"',
    'schema_state_unsafe=0',
    'if [ -e "$SCHEMA_STATE_FILE" ]; then',
    '  CURRENT_SCHEMA_COMPATIBILITY="$(cat "$SCHEMA_STATE_FILE")"',
    '  if ! validate_schema_compatibility "$CURRENT_SCHEMA_COMPATIBILITY"; then',
    '    echo "The durable database compatibility marker is invalid" >&2',
    '    SCHEMA_MUTATION_STARTED=1',
    '    enter_schema_maintenance || true',
    '    exit 78',
    '  fi',
    'fi',
    'if [ -e "$SCHEMA_PENDING_FILE" ]; then',
    '  pending_compatibility="$(cat "$SCHEMA_PENDING_FILE")"',
    '  SCHEMA_MUTATION_STARTED=1',
    '  if ! validate_schema_compatibility "$pending_compatibility" || [ "$pending_compatibility" != "$EXPECTED_SCHEMA_COMPATIBILITY" ]; then',
    '    echo "An unfinished schema transition requires a release with compatibility $pending_compatibility, not $EXPECTED_SCHEMA_COMPATIBILITY" >&2',
    '    enter_schema_maintenance || true',
    '    exit 78',
    '  fi',
    '  if [ "$pending_compatibility" != "$PREVIOUS_SCHEMA_COMPATIBILITY" ]; then schema_state_unsafe=1; fi',
    'fi',
    'if [ "$CURRENT_SCHEMA_COMPATIBILITY" != "$PREVIOUS_SCHEMA_COMPATIBILITY" ]; then',
    '  echo "The active backend is not compatible with the durable database state; maintaining API isolation until roll-forward" >&2',
    '  SCHEMA_MUTATION_STARTED=1',
    '  schema_state_unsafe=1',
    '  if [ "$EXPECTED_SCHEMA_COMPATIBILITY" = "$PREVIOUS_SCHEMA_COMPATIBILITY" ]; then',
    '    enter_schema_maintenance || true',
    '    echo "Refusing to relabel a newer database state for an incompatible older backend" >&2',
    '    exit 78',
    '  fi',
    'fi',
    'if [ "$schema_state_unsafe" -eq 1 ]; then enter_schema_maintenance || exit 70; fi',

    'echo "[8/12] Applying checked-in database migrations"',
    'if [ "$PREVIOUS_SCHEMA_COMPATIBILITY" != "$EXPECTED_SCHEMA_COMPATIBILITY" ] && ! systemctl is-active --quiet intitrade-maintenance.service; then',
    '  echo "Entering maintenance before the forward-only schema boundary"',
    '  enter_schema_maintenance || exit 70',
    'fi',
    '# Close the final in-flight write race after the old API is quiesced.',
    'run_predeploy_checks',
    'schema_pending_tmp="$SCHEMA_STATE_DIR/.schema-compatibility.pending.$$.tmp"',
    'printf "%s\\n" "$EXPECTED_SCHEMA_COMPATIBILITY" > "$schema_pending_tmp"',
    'chown root:root "$schema_pending_tmp"',
    'chmod 0644 "$schema_pending_tmp"',
    'mv -f -- "$schema_pending_tmp" "$SCHEMA_PENDING_FILE"',
    'SCHEMA_MUTATION_STARTED=1',
    'runuser -u intitrade -- env -u DATABASE_URL HOME=/var/lib/intitrade NODE_ENV=production "$NODE_BIN" --env-file="$PROJECT_DIR/backend/.env" "$BUILD_DIR/backend/node_modules/prisma/build/index.js" migrate deploy --schema "$BUILD_DIR/backend/prisma/schema.prisma"',
    'runuser -u intitrade -- env -u DATABASE_URL HOME=/var/lib/intitrade NODE_ENV=production "$NODE_BIN" --env-file="$PROJECT_DIR/backend/.env" "$BUILD_DIR/backend/node_modules/prisma/build/index.js" migrate diff --from-schema-datasource="$BUILD_DIR/backend/prisma/schema.prisma" --to-schema-datamodel="$BUILD_DIR/backend/prisma/schema.prisma" --exit-code',
    'schema_state_tmp="$SCHEMA_STATE_DIR/.schema-compatibility.$$.tmp"',
    'printf "%s\\n" "$EXPECTED_SCHEMA_COMPATIBILITY" > "$schema_state_tmp"',
    'chown root:root "$schema_state_tmp"',
    'chmod 0644 "$schema_state_tmp"',
    'mv -f -- "$schema_state_tmp" "$SCHEMA_STATE_FILE"',
    'rm -f -- "$SCHEMA_PENDING_FILE"',
    'SCHEMA_MIGRATIONS_COMPLETE=1',

    'echo "[9/12] Activating and verifying the backend release"',
    'BACKEND_ACTIVATED=1',
    'PROJECT_DIR="$PROJECT_DIR" BACKEND_RELEASE_MODE=activate BACKEND_REQUIRED_SCHEMA_COMPATIBILITY="$EXPECTED_SCHEMA_COMPATIBILITY" bash deploy/build-backend-release.sh',
    'PROJECT_DIR="$PROJECT_DIR" SERVER_API_PORT="$API_PORT" OPERATIONS_MODE=activate PROJECT_PERMISSIONS_PREPARED=1 bash deploy/configure-operations.sh',
    'if command -v pm2 >/dev/null 2>&1 && pm2 describe university-marketplace-api >/dev/null 2>&1; then pm2 delete university-marketplace-api >/dev/null 2>&1 || true; pm2 save --force >/dev/null 2>&1 || true; fi',
    'start_api_service',
    'ready=0',
    'for attempt in $(seq 1 30); do',
    '  health="$(curl --fail --silent --show-error --connect-timeout 2 --max-time 5 "http://127.0.0.1:$API_PORT/api/health/ready" 2>/dev/null || true)"',
    '  if systemctl is-active --quiet intitrade-api.service && verify_health_json "$health" "$EXPECTED_VERSION"; then ready=1; break; fi',
    '  sleep 1',
    'done',
    'if [ "$ready" -ne 1 ]; then echo "The new API release did not become ready" >&2; exit 1; fi',
    'NEW_BACKEND_VERIFIED=1',
    'rm -f -- "$MAINTENANCE_STATE_FILE"',
    'rm -f -- "$UPLOAD_CLEANUP_PAUSED"',

    'echo "[10/12] Activating the frontend and transactional Nginx configuration"',
    'FRONTEND_ACTIVATED=1',
    'PROJECT_DIR="$PROJECT_DIR" FRONTEND_RELEASE_MODE=activate bash deploy/build-frontend-release.sh',
    'NGINX_TRANSACTION_DIR="/var/backups/nginx/intitrade-deploy-$EXPECTED_VERSION-$(date -u +%s%N)-$$"',
    'PROJECT_DIR="$PROJECT_DIR" NGINX_TRANSACTION_DIR="$NGINX_TRANSACTION_DIR" bash deploy/configure-intitrade-nginx.sh',
    'NGINX_CONFIGURED=1',

    'echo "[11/12] Polling the exact origin and public domains for the activated release"',
    'VERIFY_TOKEN="${EXPECTED_VERSION}-$(date -u +%s%N)-$$"',
    'EXPECTED_ENTRY_ASSET="$(find_entry_asset frontend/current/index.html)"',
    'test -n "$EXPECTED_ENTRY_ASSET"',
    'test -s "frontend/current${EXPECTED_ENTRY_ASSET}"',
    'origin_ready=0',
    'for attempt in $(seq 1 6); do',
    '  if curl --noproxy "*" --resolve "intitrade.shop:443:127.0.0.1" --fail --silent --show-error --connect-timeout 2 --max-time 3 --header "Cache-Control: no-cache" "https://intitrade.shop/?deploy=${VERIFY_TOKEN}-${attempt}" --output "$BUILD_DIR/origin-index.html" \\',
    '    && cmp --silent frontend/current/index.html "$BUILD_DIR/origin-index.html"; then origin_ready=1; break; fi',
    '  sleep 1',
    'done',
    'if [ "$origin_ready" -ne 1 ]; then echo "Nginx origin did not expose the activated frontend release" >&2; exit 1; fi',
    'verify_public_frontend "https://intitrade.shop" "$BUILD_DIR/primary-index.html" & primary_frontend_pid=$!',
    'verify_public_frontend "https://www.intitrade.shop" "$BUILD_DIR/www-index.html" & www_frontend_pid=$!',
    'verify_public_frontend "https://adelina.adilkan.com" "$BUILD_DIR/alternate-index.html" & alternate_frontend_pid=$!',
    'frontend_check_failed=0',
    'for check_pid in "$primary_frontend_pid" "$www_frontend_pid" "$alternate_frontend_pid"; do if ! wait "$check_pid"; then frontend_check_failed=1; fi; done',
    'if [ "$frontend_check_failed" -ne 0 ]; then exit 1; fi',
    'verify_public_health "https://intitrade.shop" & primary_health_pid=$!',
    'verify_public_health "https://adelina.adilkan.com" & alternate_health_pid=$!',
    'health_check_failed=0',
    'for check_pid in "$primary_health_pid" "$alternate_health_pid"; do if ! wait "$check_pid"; then health_check_failed=1; fi; done',
    'if [ "$health_check_failed" -ne 0 ]; then exit 1; fi',
    'systemctl is-active --quiet intitrade-api.service',

    'echo "[12/12] Recording deployment and retiring an empty root PM2 runtime"',
    `if command -v pm2 >/dev/null 2>&1 && pm2 jlist 2>/dev/null | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{process.exit(JSON.parse(s).length===0?0:1)}catch{process.exit(1)}})'; then pm2 kill >/dev/null 2>&1 || true; systemctl disable --now pm2-root.service >/dev/null 2>&1 || true; fi`,
    'mkdir -p /var/log/intitrade',
    `printf '{"deployedAt":"%s","commit":"%s","status":"success"}\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$EXPECTED_VERSION" >> /var/log/intitrade/deployments.jsonl`,
    'systemctl status intitrade-api.service --no-pager --lines=10',
    'echo "Deployment completed successfully"'
  ].join('\n');

  conn.exec('bash -s', (error, stream) => {
    if (error) {
      console.error('Could not start the remote deployment transaction:', error.message);
      process.exitCode = 1;
      conn.end();
      return;
    }

    stream.on('close', (code, signal) => {
      if (code !== 0) {
        console.error(`Deployment stopped with code ${code ?? 'unknown'}${signal ? ` (${signal})` : ''}`);
        process.exitCode = code || 1;
      }
      conn.end();
    }).on('data', (data) => process.stdout.write(data));
    stream.stderr.on('data', (data) => process.stderr.write(data));
    stream.end(`${script}\n`);
  });
}).connect(config);

conn.on('error', (error) => {
  console.error('SSH connection failed:', error.message);
  process.exitCode = 1;
});
